Uploaded First Draft of Seminar 19
alexfertel/reports pull request #26
Opened 2020-04-23 19:58 UTC by JDavid17

First Draft

2020-05-12 22:14 UTC, alexfertel requested changes

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +
```suggestion
No hace falta añadir los integrantes del equipo, ni la tabla de contenidos (ToC)
```

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Para este seminario debemos proponer e implementar un mecanismo de contratos al estilo de ``CodeContract`` en el lenguaje ***Python***. Con nuestra implementación deberíamos ser capaces de hacer algo
Tampoco hace falta la orden

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe estar libre de efectos colaterales**, y que debe **cumplirse como requisito para ejecutar el método al que está asociada**. Un uso frecuente de las **pre-condici
Mmmm, depende del concepto de validar. Yo pudiera argumentar que tener tipado estático elimina algunas validaciones que hicieran falta en lenguajes con tipado dinámico.

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe cumplirse luego de la ejecución del método**, y funge como garantía de lo que éste hace. Por tanto, las **pos-condiciones** **son evaluadas justo después de ejec
Qué es funge?

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Primero debemos aclarar algunas características del lenguaje `Python` y como funcionan sus funciones, que les serán útiles para entender decoradores.
Ese "como" lleva tilde

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Primero debemos aclarar algunas características del lenguaje `Python` y como funcionan sus funciones, que les serán útiles para entender decoradores.
No hables refiriéndote al lector. "Primero aclaremos algunas características de `Python`, en particular el comportamiento de las funciones."

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Esto significa que las funciones en `Python` son objetos y como cualquier otro objeto puede ser pasadas y usadas como argumentos:
pueden*

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +En este ejemplo tenemos 3 funciones `say_hello()` y `be_awesome()` son funciones normales que esperan un parámetro `name` de tipo *string*. La función `gree_bob()` sin embargo espera una función como
`greet_bob`*. Además fijense que la función es el objeto sin paréntesis, es decir, `greet_bob`, no `greet_bob`, lo segundo se refiere al resultado de llamar a la funcion, en general deberían quitarlos dondequiera que lo usen.

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Importante notar aquí como las funciones `say_hello()` y `be_awesome()` son llamadas sin los paréntesis, esto significa que solo una referencia a la función es pasada como parámetro.
Me parece que no tienen claro bien lo que significa que las funciones sean objetos. `greet_bob(be_awesome)` está llamando a la función `greet_bob` con `be_awesome` como argumentos, *en ningun momento se "llama" a `be_awesome`*. Lo que significa es simplemente lo que significaría en cualquier lenguaje que ud conocen: *se le pasa una **copia** de la referencia al objeto `be_awesome`*. Arreglen este pedazo en base a lo anterior.

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Notar que estamos retornado una referencia a las funciones, así que la siguiente salida es lo esperado.
retornando*. No escribiría esto así referirse al comentario anterior.

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Ahora que ya hemos visto algunas características de las funciones en `Python` veamos que son los decoradores.
qué*

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +En este ejemplo el decorador ocurre en la linea `say_whee = my_decorator(say_whee)`, la variable `say_whee` ahora apunta al `wrapper` que se define dentro de `my_decorator`. Pero `wrapper` tiene una
"el decorador ocurre"? Tal vez "el decorado ocurre" o  "la decoración ocurre". "apunta", "`wrapper` tiene una referencia", "es la que ejecuta (la referencia)" creo que no son la mejor forma de explicar lo que pasa.

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +En simples términos:  ***decorators wrap a function, modifying its behavior.***
Nunca usen frases en inglés por gusto, cuál es el objetivo de poner esta línea, justo debajo la escriben en español.

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Recordemos que nuestro decorador [my_decorator](#my_decorator) retorna una referencia a `wrapper` y esta es una función que no recibe ningún argumento. Esto se podría arreglar simplemente agregándole
además* número*. "...arbitrario de *argumentos*".

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Además de decorar funciones también podemos decorar clases. Las clases pueden ser decoradas de dos maneras. Primero por supuesto puede simplemente decorar los métodos de la clase que quieras, en `Pyt
más*

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Decorar una clase, no es muy distinto que decorar una función. Por supuesto la diferencia esta en que el decorador en lugar de recibir una función como argumento, recibe una clase. El decorador que v
Esa coma al principio sobra. está* funcionará* más*

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +##### Librerías usadas:
Bibliotecas

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +##### Librerías usadas:
Librerias con tilde?

2020-05-12 22:14 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +En nuestra solución no se encuentra implementado el ***feature*** de Diseño por Contratos donde se puede tener acceso al valor de una variable antes de la ejecución del método, analicemos primero que
Me parece que no es tan complicado, pero tienen razón en que no es objetivo del seminario. Faltan varias tildes en este párrafo. En general el seminario está muy bien, lo que tienen detalles de redacción, por favor, arréglenlos con detenimiento.

2020-05-14 19:52 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe estar libre de efectos colaterales**, y que debe **cumplirse como requisito para ejecutar el método al que está asociada**. Un uso frecuente de las **pre-condici
No me queda claro que quieres decir con esto. Lo que hacemos referencia es a las validaciones que no se satisfacen solo con tipado. Por ejemplo la pre-condicion que `cnt >= 0` no basta con saber que `cnt` es de tipo `int`. 🤔

2020-05-14 19:59 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe cumplirse luego de la ejecución del método**, y funge como garantía de lo que éste hace. Por tanto, las **pos-condiciones** **son evaluadas justo después de ejec
Eso fue sacado del libro de Katrib :). Lo puedo cambiar supongo.
```suggestion
    Es una cláusula lógica que **debe cumplirse luego de la ejecución del método**, y sirve como garantía de lo que éste hace. Por tanto, las **pos-condiciones** **son evaluadas justo después de ejecutado el método** y **antes de retornar al código que llama**.
```

2020-05-14 20:03 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Primero debemos aclarar algunas características del lenguaje `Python` y como funcionan sus funciones, que les serán útiles para entender decoradores.
😃 
```suggestion
Primero aclaremos algunas características del lenguaje `Python`, en particular el comportamiento de sus funciones.
```

2020-05-14 20:03 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Esto significa que las funciones en `Python` son objetos y como cualquier otro objeto puede ser pasadas y usadas como argumentos:
```suggestion
Esto significa que las funciones en `Python` son objetos y como cualquier otro objeto pueden ser pasadas y usadas como argumentos:
```

2020-05-14 20:13 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Importante notar aquí como las funciones `say_hello()` y `be_awesome()` son llamadas sin los paréntesis, esto significa que solo una referencia a la función es pasada como parámetro.
A ver eso nos queda claro, `greet_bob` recibe la referencia a una funcion como argumento (lo cual recalcamos mas abajo) 
**Importante notar aquí como las funciones `say_hello()` y `be_awesome()` son usadas sin los paréntesis, esto significa que solo una referencia a la función es pasada como parámetro.,** 

Pero en el cuerpo de `greet_bob` se llama/ejecuta esa funcion que recibe como parametro. No entiendo donde se dice algo que no esta bien

2020-05-14 20:21 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Notar que estamos retornado una referencia a las funciones, así que la siguiente salida es lo esperado.
```suggestion
Notar que estamos retornado una copia de la referencia a esas funciones, así que la siguiente salida es lo esperado.
```

2020-05-14 20:31 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Ahora que ya hemos visto algunas características de las funciones en `Python` veamos que son los decoradores.
```suggestion
Ahora qué ya hemos visto algunas características de las funciones en `Python` veamos que son los decoradores.
```

2020-05-14 20:47 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +En este ejemplo el decorador ocurre en la linea `say_whee = my_decorator(say_whee)`, la variable `say_whee` ahora apunta al `wrapper` que se define dentro de `my_decorator`. Pero `wrapper` tiene una
```suggestion
En este ejemplo la acción de decorar ocurre en `say_whee = my_decorator(say_whee)`, `my_decorator()` es una función que retorna una copia de la referencia a la función `wapper` que se define dentro del mismo, luego la variable `say_whee` tiene la copia de esta referencia. Y a su vez  `wrapper` tiene una copia de la referencia a la función original `say_whee` y es esta la que ejecuta entre los dos `prints`.
```

2020-05-15 00:34 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe estar libre de efectos colaterales**, y que debe **cumplirse como requisito para ejecutar el método al que está asociada**. Un uso frecuente de las **pre-condici
Que hay cosas que si puedes validar teniendo tipado estático, por ejemplo, `type(cnt) == int` chequearía que `cnt` sea entero, sin embargo, esto es algo que no tienes que validar en un lenguaje estáticamente tipado, en Python si lo tendrías que hacer: la precondición `cnt >= 0` falla si `cnt` no es entero. Por eso digo que la definición de validar depende, porque yo pudiera interpretar que estas diciendo: "El tipado estático de los parámetros no es suficiente para validar la entrada" y esto depende de qué validación vayas a hacer. Hay veces que si es suficiente :)

2020-05-15 00:37 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Notar que estamos retornado una referencia a las funciones, así que la siguiente salida es lo esperado.
retornando*

2020-05-15 00:37 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Importante notar aquí como las funciones `say_hello()` y `be_awesome()` son llamadas sin los paréntesis, esto significa que solo una referencia a la función es pasada como parámetro.
Si, lo único que yo quitaría los paréntesis :)

2020-05-15 00:38 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Ahora que ya hemos visto algunas características de las funciones en `Python` veamos que son los decoradores.
jajaja, papa es el otro que....

2020-05-15 00:39 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +En este ejemplo el decorador ocurre en la linea `say_whee = my_decorator(say_whee)`, la variable `say_whee` ahora apunta al `wrapper` que se define dentro de `my_decorator`. Pero `wrapper` tiene una
Jajaja, que enredo....

2020-05-15 18:03 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe estar libre de efectos colaterales**, y que debe **cumplirse como requisito para ejecutar el método al que está asociada**. Un uso frecuente de las **pre-condici
```suggestion
    Es una cláusula lógica que **debe estar libre de efectos colaterales**, y que debe **cumplirse como requisito para ejecutar el método al que está asociada**. Un uso frecuente de las **pre-condiciones** es validar aserciones en los parámetros de entrada a los métodos que no puede satisfacerse solo con la declaración y tipado estático de los mismo.
```
Que tal asi?

2020-05-15 18:22 UTC, JDavid17 commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +Importante notar aquí como las funciones `say_hello()` y `be_awesome()` son llamadas sin los paréntesis, esto significa que solo una referencia a la función es pasada como parámetro.
```suggestion
Importante notar aquí como las funciones `say_hello` y `be_awesome` son usadas sin los paréntesis, esto significa que solo una copia de la referencia a esa función es pasada como parámetro.
```

2020-05-16 02:42 UTC, alexfertel commented on src/grupo_2/equipo_2_seminario_19/Readme.md
> +    Es una cláusula lógica que **debe estar libre de efectos colaterales**, y que debe **cumplirse como requisito para ejecutar el método al que está asociada**. Un uso frecuente de las **pre-condici
Forget it, déjalo así, esto es metatranca mía...no es importante

2020-05-24 13:56 UTC, alexfertel approved these changes

2020-05-24 13:56 UTC, merged